# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for ACTRA
# Generated by scripts/build_release.py

import sys
from pathlib import Path

block_cipher = None

PROJECT_ROOT = r'D:/Ai Ai/radioproject_git'

a = Analysis(
    [PROJECT_ROOT + '/desktop-app/webview_launcher.py'],
    pathex=[
        PROJECT_ROOT,
        PROJECT_ROOT + '/desktop-app',
    ],
    binaries=[],
    datas=[
    (r'D:/Ai Ai/radioproject_git/frontend', 'frontend'),
    (r'D:/Ai Ai/radioproject_git/common', 'common'),
    (r'D:/Ai Ai/radioproject_git/task_system', 'task_system'),
    (r'D:/Ai Ai/radioproject_git/desktop-app/api', 'desktop-app/api'),
    (r'D:/Ai Ai/radioproject_git/desktop-app/logic', 'desktop-app/logic'),
    (r'D:/Ai Ai/radioproject_git/desktop-app/services', 'desktop-app/services'),
    (r'D:/Ai Ai/radioproject_git/desktop-app/tools', 'desktop-app/tools'),
    (r'D:/Ai Ai/radioproject_git/config.json', '.'),
    (r'D:/Ai Ai/radioproject_git/desktop-app/server.py', 'desktop-app'),
    ],
    hiddenimports=[
        'flask',
        'flask.json',
        'werkzeug',
        'werkzeug.serving',
        'werkzeug.utils',
        'webview',
        'webview.platforms.winforms',
        'clr_loader',
        'pythonnet',
        'pydantic',
        'pydantic.deprecated',
        'pydantic.deprecated.decorator',
        'bcrypt',
        'PIL',
        'PIL.Image',
        'Levenshtein',
        'pymorphy2',
        'pymorphy2.units',
        'packaging',
        'task_system',
        'task_system.core',
        'task_system.types',
        'task_system.models',
        'common',
        'common.config_loader',
        'common.extension_points_config',
        'common.watchdog',
        'services',
        'logic',
        'api',
        'api.session_api',
        'api.calendar_api',
        'api.complexes_api',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'scipy',
        'pandas',
        'numpy',
        'IPython',
        'jupyter',
        'notebook',
        # Force non-Qt packaging path (pywebview WinForms on Windows).
        'qtpy',
        'PyQt5',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
        'PyQt5.QtWebEngineCore',
        'PyQt5.QtWebEngineWidgets',
        'PyQt6',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'PyQt6.QtWebEngineCore',
        'PyQt6.QtWebEngineWidgets',
        'PySide2',
        'PySide6',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='ACTRA',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=r'D:/Ai Ai/radioproject_git/frontend/assets/actra_white.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='ACTRA',
)
