// add_microcards_keys.js — adds microcards locale section to all three locale files
const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, 'frontend', 'assets', 'locales');

const sections = {
  ru: {
    page_heading: 'Микрокарточки',
    subtitle_default: 'Повторение и обучение',
    subtitle_session: 'Сессия повторения',
    subtitle_summary: 'Результаты сессии',
    streak_aria: 'Серия активности',
    editor_btn: 'Редактор',
    editor_title: 'Открыть в редакторе',
    editor_link_btn: 'Открыть редактор',
    stat_due_label: 'К повтору',
    stat_new_label: 'Новых',
    stat_today_label: 'Сегодня',
    refresh_btn: 'Обновить',
    search_placeholder: 'Найти колоду по названию или теме',
    search_aria: 'Поиск по колодам',
    filter_list_aria: 'Фильтры колод',
    filter_all: 'Все',
    filter_urgent: 'Срочно',
    filter_new: 'Есть новые',
    filter_recent: 'Недавние',
    ownership_label: 'Принадлежность',
    ownership_list_aria: 'Фильтры принадлежности колод',
    own_all: 'Все',
    own_mine: 'Моё',
    own_shared: 'Общее',
    own_imported: 'Импорт',
    loading_decks: 'Загрузка колод...',
    error_load_decks_text: 'Ошибка загрузки',
    retry_btn: 'Повторить',
    back_btn: 'К колодам',
    restart_btn: 'Заново',
    restart_title: 'Начать сессию заново',
    requeue_label: 'Ошибки в очереди:',
    card_area_aria: 'Карточка',
    answer_label: 'Ответ',
    result_label: 'Результат',
    reveal_btn: 'Показать ответ',
    rate_prompt: 'Оцените знание',
    rate_group_aria: 'Оценка знания',
    btn_again: 'Снова',
    btn_hard: 'Сложно',
    btn_good: 'Хорошо',
    btn_easy: 'Легко',
    btn_again_aria: 'Снова — не знаю (клавиша 1)',
    btn_hard_aria: 'Сложно — трудно вспомнить (клавиша 2)',
    btn_good_aria: 'Хорошо — вспомнил (клавиша 3)',
    btn_easy_aria: 'Легко — очень просто (клавиша 4)',
    no_cards_title: 'Нет карточек к повторению',
    no_cards_desc: 'В этой колоде сейчас нет доступных карточек.',
    kbd_reveal: 'показать ответ',
    kbd_rate: 'оценка',
    kbd_back: 'назад',
    summary_title: 'Сессия завершена!',
    summary_deck_fallback: 'Колода',
    stat_total: 'Всего',
    stat_correct: 'Верно',
    stat_errors: 'Ошибок',
    stat_time: 'Время',
    rating_again: 'Снова',
    rating_hard: 'Сложно',
    rating_good: 'Хорошо',
    rating_easy: 'Легко',
    summary_back_btn: 'К колодам',
    summary_restart_btn: 'Повторить колоду',
    ownership_mine: 'Показываем колоды, созданные из текущего профиля. Они всё равно живут в общей библиотеке.',
    ownership_shared: 'Показываем общие колоды, созданные вне текущего профиля и не пришедшие через отдельный импорт.',
    ownership_imported: 'Показываем колоды, пришедшие через текстовый импорт.',
    ownership_all: 'Колоды живут в общей библиотеке, а прогресс по ним остаётся личным.',
    hint_no_decks: 'Когда появятся колоды, здесь можно будет быстро выбрать, что повторять первым.',
    hint_urgent_some: '{n} колод с ближайшим повторением. Сверху — самая срочная.',
    hint_urgent_none: 'Срочных повторений по текущему фильтру нет.',
    hint_new_some: '{n} колод с новыми карточками. Хороший режим для короткого входа.',
    hint_new_none: 'Новых карточек по текущему запросу нет.',
    hint_recent_some: '{n} колод, к которым ты возвращался недавно.',
    hint_recent_none: 'Недавних колод по текущему запросу не найдено.',
    hint_search: 'Найдено {visible} из {total}. Поиск работает по названию и теме колоды.',
    hint_default: 'Сначала показываем колоды с самым срочным повторением.',
    hint_local: 'Колоды живут в общей локальной библиотеке, а прогресс по ним остаётся личным. Сначала показываем самые срочные колоды.',
    mode_wip_title: 'Функционал в разработке',
    mode_wip_desc: 'Микрокарточки временно скрыты из продукта. Вернём этот режим после следующего этапа доработки.',
    error_load_decks: 'Не удалось загрузить колоды',
    error_network_decks: 'Ошибка сети при загрузке колод',
    empty_title: 'Нет колод микрокарточек',
    empty_desc: 'Создайте колоду из анализа теории в редакторе или воспользуйтесь ручным созданием.',
    empty_filter_title: 'По этому фильтру колод нет',
    empty_filter_desc: 'Снимите часть ограничений или измените поисковый запрос, чтобы увидеть другие колоды.',
    deck_name_fallback: 'Колода',
    deck_updated_recently: 'обновлена недавно',
    deck_due_suffix: 'к повтору',
    deck_done_badge: 'всё пройдено',
    deck_urgent_badge: 'Самое срочное',
    deck_new_suffix: 'новых',
    deck_btn_repeat: 'Повторять',
    deck_btn_open: 'Открыть',
    deck_restart_title: 'Начать сессию заново',
    error_open_deck: 'Не удалось открыть колоду',
    error_network_open: 'Ошибка сети при открытии колоды',
    card_fallback: 'Карточка',
    btn_check_pairs: 'Проверить пары',
    btn_reveal: 'Показать ответ',
    pair_empty: 'pair_match данные пусты.',
    session_expired: 'Сессия устарела. Возвращаемся к колодам.',
    error_save_review: 'Ошибка сохранения review',
    error_network_review: 'Ошибка сети при отправке оценки',
    user_avatar_alt: 'Пользователь',
    user_guest: 'Гость',
  },
  en: {
    page_heading: 'Microcards',
    subtitle_default: 'Review and study',
    subtitle_session: 'Review session',
    subtitle_summary: 'Session results',
    streak_aria: 'Activity streak',
    editor_btn: 'Editor',
    editor_title: 'Open in editor',
    editor_link_btn: 'Open editor',
    stat_due_label: 'Due',
    stat_new_label: 'New',
    stat_today_label: 'Today',
    refresh_btn: 'Refresh',
    search_placeholder: 'Search decks by name or topic',
    search_aria: 'Search decks',
    filter_list_aria: 'Deck filters',
    filter_all: 'All',
    filter_urgent: 'Urgent',
    filter_new: 'Has new',
    filter_recent: 'Recent',
    ownership_label: 'Ownership',
    ownership_list_aria: 'Deck ownership filters',
    own_all: 'All',
    own_mine: 'Mine',
    own_shared: 'Shared',
    own_imported: 'Imported',
    loading_decks: 'Loading decks...',
    error_load_decks_text: 'Loading error',
    retry_btn: 'Retry',
    back_btn: 'Back to decks',
    restart_btn: 'Restart',
    restart_title: 'Start session over',
    requeue_label: 'Errors in queue:',
    card_area_aria: 'Card',
    answer_label: 'Answer',
    result_label: 'Result',
    reveal_btn: 'Show answer',
    rate_prompt: 'Rate your recall',
    rate_group_aria: 'Recall rating',
    btn_again: 'Again',
    btn_hard: 'Hard',
    btn_good: 'Good',
    btn_easy: 'Easy',
    btn_again_aria: 'Again — did not know (key 1)',
    btn_hard_aria: 'Hard — hard to recall (key 2)',
    btn_good_aria: 'Good — recalled it (key 3)',
    btn_easy_aria: 'Easy — very easy (key 4)',
    no_cards_title: 'No cards due',
    no_cards_desc: 'This deck has no available cards right now.',
    kbd_reveal: 'show answer',
    kbd_rate: 'rate',
    kbd_back: 'back',
    summary_title: 'Session complete!',
    summary_deck_fallback: 'Deck',
    stat_total: 'Total',
    stat_correct: 'Correct',
    stat_errors: 'Errors',
    stat_time: 'Time',
    rating_again: 'Again',
    rating_hard: 'Hard',
    rating_good: 'Good',
    rating_easy: 'Easy',
    summary_back_btn: 'Back to decks',
    summary_restart_btn: 'Replay deck',
    ownership_mine: 'Showing decks created from the current profile. They still live in the shared library.',
    ownership_shared: 'Showing shared decks created outside the current profile and not imported separately.',
    ownership_imported: 'Showing decks that arrived via text import.',
    ownership_all: 'Decks live in the shared library; your progress on them stays personal.',
    hint_no_decks: 'Once decks appear, you can quickly choose what to review first.',
    hint_urgent_some: '{n} decks with upcoming reviews. Most urgent is on top.',
    hint_urgent_none: 'No urgent reviews match the current filter.',
    hint_new_some: '{n} decks with new cards. Great for a quick session.',
    hint_new_none: 'No new cards match the current query.',
    hint_recent_some: '{n} decks you returned to recently.',
    hint_recent_none: 'No recent decks match the current query.',
    hint_search: 'Found {visible} of {total}. Search works by deck name and topic.',
    hint_default: 'Decks with the most urgent reviews are shown first.',
    hint_local: 'Decks live in the shared local library; your progress stays personal. Most urgent decks are shown first.',
    mode_wip_title: 'Feature in development',
    mode_wip_desc: 'Microcards are temporarily hidden from the product. We will bring this mode back after the next development phase.',
    error_load_decks: 'Failed to load decks',
    error_network_decks: 'Network error while loading decks',
    empty_title: 'No microcard decks',
    empty_desc: 'Create a deck from a theory analysis in the editor, or use manual creation.',
    empty_filter_title: 'No decks match this filter',
    empty_filter_desc: 'Remove some constraints or change the search query to see other decks.',
    deck_name_fallback: 'Deck',
    deck_updated_recently: 'updated recently',
    deck_due_suffix: 'due',
    deck_done_badge: 'all done',
    deck_urgent_badge: 'Most urgent',
    deck_new_suffix: 'new',
    deck_btn_repeat: 'Review',
    deck_btn_open: 'Open',
    deck_restart_title: 'Start session over',
    error_open_deck: 'Failed to open deck',
    error_network_open: 'Network error while opening deck',
    card_fallback: 'Card',
    btn_check_pairs: 'Check pairs',
    btn_reveal: 'Show answer',
    pair_empty: 'pair_match data is empty.',
    session_expired: 'Session expired. Returning to decks.',
    error_save_review: 'Error saving review',
    error_network_review: 'Network error while submitting rating',
    user_avatar_alt: 'User',
    user_guest: 'Guest',
  },
  uk: {
    page_heading: 'Мікрокартки',
    subtitle_default: 'Повторення і навчання',
    subtitle_session: 'Сесія повторення',
    subtitle_summary: 'Результати сесії',
    streak_aria: 'Серія активності',
    editor_btn: 'Редактор',
    editor_title: 'Відкрити в редакторі',
    editor_link_btn: 'Відкрити редактор',
    stat_due_label: 'До повторення',
    stat_new_label: 'Нових',
    stat_today_label: 'Сьогодні',
    refresh_btn: 'Оновити',
    search_placeholder: 'Знайти колоду за назвою або темою',
    search_aria: 'Пошук колод',
    filter_list_aria: 'Фільтри колод',
    filter_all: 'Усі',
    filter_urgent: 'Термінові',
    filter_new: 'Є нові',
    filter_recent: 'Недавні',
    ownership_label: 'Належність',
    ownership_list_aria: 'Фільтри належності колод',
    own_all: 'Усі',
    own_mine: 'Моє',
    own_shared: 'Спільне',
    own_imported: 'Імпорт',
    loading_decks: 'Завантаження колод...',
    error_load_decks_text: 'Помилка завантаження',
    retry_btn: 'Повторити',
    back_btn: 'До колод',
    restart_btn: 'Заново',
    restart_title: 'Почати сесію заново',
    requeue_label: 'Помилки в черзі:',
    card_area_aria: 'Картка',
    answer_label: 'Відповідь',
    result_label: 'Результат',
    reveal_btn: 'Показати відповідь',
    rate_prompt: 'Оцініть знання',
    rate_group_aria: 'Оцінка знань',
    btn_again: 'Знову',
    btn_hard: 'Важко',
    btn_good: 'Добре',
    btn_easy: 'Легко',
    btn_again_aria: 'Знову — не знаю (клавіша 1)',
    btn_hard_aria: 'Важко — важко згадати (клавіша 2)',
    btn_good_aria: 'Добре — згадав (клавіша 3)',
    btn_easy_aria: 'Легко — дуже просто (клавіша 4)',
    no_cards_title: 'Немає карток до повторення',
    no_cards_desc: 'У цій колоді зараз немає доступних карток.',
    kbd_reveal: 'показати відповідь',
    kbd_rate: 'оцінка',
    kbd_back: 'назад',
    summary_title: 'Сесію завершено!',
    summary_deck_fallback: 'Колода',
    stat_total: 'Всього',
    stat_correct: 'Вірно',
    stat_errors: 'Помилок',
    stat_time: 'Час',
    rating_again: 'Знову',
    rating_hard: 'Важко',
    rating_good: 'Добре',
    rating_easy: 'Легко',
    summary_back_btn: 'До колод',
    summary_restart_btn: 'Повторити колоду',
    ownership_mine: 'Показуємо колоди, створені з поточного профілю. Вони все одно живуть у спільній бібліотеці.',
    ownership_shared: 'Показуємо спільні колоди, створені поза поточним профілем і не додані через окремий імпорт.',
    ownership_imported: 'Показуємо колоди, що надійшли через текстовий імпорт.',
    ownership_all: 'Колоди живуть у спільній бібліотеці, а прогрес залишається особистим.',
    hint_no_decks: 'Коли з\'являться колоди, тут можна буде швидко обрати, що повторювати першим.',
    hint_urgent_some: '{n} колод з найближчим повторенням. Вгорі — найтерміновіша.',
    hint_urgent_none: 'Термінових повторень за поточним фільтром немає.',
    hint_new_some: '{n} колод з новими картками. Хороший режим для короткого входу.',
    hint_new_none: 'Нових карток за поточним запитом немає.',
    hint_recent_some: '{n} колод, до яких ти повертався нещодавно.',
    hint_recent_none: 'Нещодавніх колод за поточним запитом не знайдено.',
    hint_search: 'Знайдено {visible} з {total}. Пошук працює за назвою та темою колоди.',
    hint_default: 'Спочатку показуємо колоди з найтерміновішим повторенням.',
    hint_local: 'Колоди живуть у спільній локальній бібліотеці, а прогрес залишається особистим. Спочатку показуємо найтерміновіші колоди.',
    mode_wip_title: 'Функціонал у розробці',
    mode_wip_desc: 'Мікрокартки тимчасово приховані з продукту. Повернемо цей режим після наступного етапу доопрацювання.',
    error_load_decks: 'Не вдалося завантажити колоди',
    error_network_decks: 'Помилка мережі при завантаженні колод',
    empty_title: 'Немає колод мікрокарток',
    empty_desc: 'Створіть колоду з аналізу теорії в редакторі або скористайтеся ручним створенням.',
    empty_filter_title: 'За цим фільтром колод немає',
    empty_filter_desc: 'Зніміть частину обмежень або змініть пошуковий запит, щоб побачити інші колоди.',
    deck_name_fallback: 'Колода',
    deck_updated_recently: 'оновлено нещодавно',
    deck_due_suffix: 'до повторення',
    deck_done_badge: 'все пройдено',
    deck_urgent_badge: 'Найтерміновіше',
    deck_new_suffix: 'нових',
    deck_btn_repeat: 'Повторювати',
    deck_btn_open: 'Відкрити',
    deck_restart_title: 'Почати сесію заново',
    error_open_deck: 'Не вдалося відкрити колоду',
    error_network_open: 'Помилка мережі при відкритті колоди',
    card_fallback: 'Картка',
    btn_check_pairs: 'Перевірити пари',
    btn_reveal: 'Показати відповідь',
    pair_empty: 'pair_match дані порожні.',
    session_expired: 'Сесія застаріла. Повертаємось до колод.',
    error_save_review: 'Помилка збереження review',
    error_network_review: 'Помилка мережі при надсиланні оцінки',
    user_avatar_alt: 'Користувач',
    user_guest: 'Гість',
  },
};

for (const [lang, keys] of Object.entries(sections)) {
  const filePath = path.join(localesDir, `${lang}.json`);
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));

  if (data.microcards) {
    console.log(`[${lang}.json] microcards section already exists — merging`);
    let added = 0;
    for (const [k, v] of Object.entries(keys)) {
      if (data.microcards[k] === undefined) { data.microcards[k] = v; added++; }
    }
    console.log(`  Added ${added} keys`);
  } else {
    data.microcards = keys;
    console.log(`[${lang}.json] Created microcards section with ${Object.keys(keys).length} keys`);
  }

  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n', 'utf8');
}

console.log('Done.');
