services:
  app:
    volumes:
      - ./desktop-app:/app/desktop-app
      - ./frontend:/app/frontend
      - ./task_system:/app/task_system
      - ./common:/app/common

  postgres:
    ports:
      - "5432:5432"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"

  mailpit:
    ports:
      - "1025:1025"