// Extracted TestUI module from S1/index.html
// NOTE: This file is generated by refactoring and should stay in sync with S1 logic.

const TestUI = (function () {
  let currentInstance = null;

  function buildAnswerProgressFromState(state) {
    const totalQuestions = Array.isArray(state && state.questions)
      ? state.questions.length
      : 0;
    const answers = state && state.answers && typeof state.answers === "object"
      ? state.answers
      : {};
    const answeredIds = new Set();

    Object.keys(answers).forEach((qid) => {
      const value = answers[qid];
      if (value == null) return;
      if (Array.isArray(value)) {
        if (value.length > 0) answeredIds.add(String(qid));
        return;
      }
      if (typeof value === "string") {
        if (value.trim().length > 0) answeredIds.add(String(qid));
        return;
      }
      answeredIds.add(String(qid));
    });

    const answeredCount = answeredIds.size;
    const unansweredCount = Math.max(0, totalQuestions - answeredCount);

    return {
      totalQuestions,
      answeredCount,
      unansweredCount,
      allAnswered: totalQuestions > 0 && unansweredCount === 0,
    };
  }

  function createRoot(containerElement, task) {
    if (!containerElement) {
      return null;
    }

    const core = (typeof TestUICore !== "undefined" && TestUICore) || null;
    const state = core && typeof core.createInitialState === "function"
      ? core.createInitialState(task)
      : (function fallbackCreateState() {
        // Fallback на случай, если TestUICore не подключен (например, старые окружения)
        const td = task && task.task_data;
        let raw = [];
        if (td && td.content && Array.isArray(td.content.questions)) {
          raw = td.content.questions;
        } else if (td && Array.isArray(td.questions)) {
          raw = td.questions;
        }

        const mapped = raw.map((q, idx) => ({
          id: q.id != null ? String(q.id) : `q_${idx + 1}`,
          index: idx,
          text: q.text || q.title || "Question",
        }));

        const testType =
          (td && td.content && td.content.test_type) || (td && td.test_type) || "single_choice";

        const content = td && td.content;
        const difficultyFromTask =
          (task && (task.difficulty || (task.task_data && task.task_data.difficulty))) ||
          null;
        const isLevel2OrHigher =
          typeof difficultyFromTask === "number" && difficultyFromTask >= 2;

        const requiresTextInput = !!(content && content.requires_text_input);
        const showOptions =
          content && Object.prototype.hasOwnProperty.call(content, "show_options")
            ? !!content.show_options
            : true;
        // L2 open-mode: либо явно требует текстового ввода, либо скрывает варианты,
        // либо уровень сложности 2+ (для второй итерации показываем поле ввода).
        const isOpenMode = requiresTextInput || !showOptions || isLevel2OrHigher;

        const difficulty = difficultyFromTask;

        const questionResults = {};

        return {
          questions: mapped,
          rawQuestions: raw,
          testType,
          currentIndex: 0,
          selections: {},
          answers: {},
          isOpenMode,
          flags: {},
          // Индексы посещённых вопросов (для sidebar: Visited/Not visited)
          visitedIndices: { 0: true },
          mode: "answering",
          difficulty: difficultyFromTask,
          questionResults: {},
        };
      })();

    // Нормализуем режимы в зависимости от сложности, независимо от источника state
    const difficultyFromTask =
      (task && (task.difficulty || (task.task_data && task.task_data.difficulty))) ||
      null;

    if (typeof difficultyFromTask === "number") {
      if (state && typeof state === "object") {
        if (state.difficulty == null) {
          state.difficulty = difficultyFromTask;
        }
        if (difficultyFromTask >= 2) {
          state.isOpenMode = true;
        }
      }
    }

    let root;
    let sidebar;
    let list;
    let main;

    const layout = (typeof TestUILayout !== "undefined" && TestUILayout) || null;
    const usingCustomLayout = !!(layout && typeof layout.createLayout === "function");

    // Гарантируем наличие visitedIndices в состоянии
    if (!state.visitedIndices) {
      state.visitedIndices = { [state.currentIndex]: true };
    }

    function emitAnswerStateChanged() {
      const progress = buildAnswerProgressFromState(state);
      try {
        if (typeof window !== "undefined" && typeof window.dispatchEvent === "function" && typeof CustomEvent === "function") {
          window.dispatchEvent(new CustomEvent("test:answer-state-changed", { detail: progress }));
        }
      } catch (e) {
        // ignore
      }
      return progress;
    }

    if (usingCustomLayout) {
      const created = layout.createLayout();
      root = created.root;
      sidebar = created.sidebar;
      list = created.list;
      main = created.main;
    } else {
      // Fallback layout без кастомного модуля: повторяем структуру L1-M1/L1-SPEC
      root = document.createElement("div");
      root.className =
        "grid gap-8 lg:grid-cols-3 xl:grid-cols-4 items-start";

      main = document.createElement("div");
      main.className =
        "lg:col-span-2 xl:col-span-3 flex min-h-[120px] flex-col gap-2";

      sidebar = document.createElement("aside");
      sidebar.className =
        "lg:col-span-1 xl:col-span-1 flex flex-col";

      const sidebarCard = document.createElement("div");
      sidebarCard.className =
        "sticky top-0 rounded-xl border border-border-strong bg-surface-2 p-6 shadow-lg dark:border-border-strong dark:bg-surface-2 h-fit";

      const sidebarTitle = document.createElement("h3");
      sidebarTitle.className =
        "text-lg font-bold text-text-main dark:text-text-on-dark mb-4";
      sidebarTitle.textContent = "Question Panel";
      sidebarCard.appendChild(sidebarTitle);

      list = document.createElement("ol");
      list.className = "grid grid-cols-5 gap-2";
      sidebarCard.appendChild(list);
      sidebar.appendChild(sidebarCard);

      root.appendChild(main);
      root.appendChild(sidebar);
    }

    function renderQuestionSidebarC1() {
      const sidebarModule =
        (typeof TestUISidebar !== "undefined" && TestUISidebar) || null;

      if (sidebarModule && typeof sidebarModule.renderSidebar === "function") {
        sidebarModule.renderSidebar({
          state,
          listElement: list,
          onSelectQuestion: (idx) => {
            state.currentIndex = idx;
            state.visitedIndices = state.visitedIndices || {};
            state.visitedIndices[idx] = true;
            renderQuestionSidebarC1();
            renderQuestionViewC2C3C4();
          },
        });
        return;
      }

      // Fallback на инлайн-реализацию, если модуль сайдбара не подключен
      list.innerHTML = "";
      if (state.questions.length === 0) {
        const empty = document.createElement("li");
        empty.className =
          "col-span-4 rounded-md border-2 border-dashed border-border-strong bg-surface-2 px-2 py-2 text-center text-xs text-text-muted dark:border-border-strong dark:bg-surface-2 dark:text-text-muted";
        empty.textContent = "No questions";
        list.appendChild(empty);
        return;
      }

      state.questions.forEach((q, idx) => {
        const item = document.createElement("li");
        const isCurrent = idx === state.currentIndex;
        const isAnswered = !!state.selections[q.id];
        const isFlagged = !!state.flags[q.id];
        const qr = state.questionResults && state.questionResults[q.id];
        const status = qr && qr.status;

        let baseClass =
          "relative flex items-center justify-center size-9 md:size-10 rounded-lg border-2 border-border-strong bg-surface-2 text-xs font-semibold text-text-main cursor-pointer select-none transition-colors dark:border-border-strong dark:bg-surface-2 dark:text-text-on-dark ";

        if (isCurrent && !status) {
          baseClass =
            "relative flex items-center justify-center size-9 md:size-10 rounded-lg bg-primary text-primary-fg text-xs font-semibold cursor-pointer select-none shadow-sm transition-colors";
        } else if (!status && isAnswered) {
          baseClass =
            "relative flex items-center justify-center size-9 md:size-10 rounded-lg bg-primary text-primary-fg text-xs font-semibold cursor-pointer select-none transition-colors";
        } else if (!status && !isAnswered) {
          baseClass +=
            "bg-surface-2 hover:bg-surface-2 dark:bg-surface-2 dark:hover:bg-bg-hover ";
        }

        if (state.mode === "review" && status) {
          if (status === "correct") {
            baseClass +=
              "border-2 border-success bg-success-light dark:bg-success-light text-success-text dark:text-success-light ";
          } else if (status === "incorrect") {
            baseClass +=
              "border-2 border-error bg-error-light dark:bg-error-light text-error-dark dark:text-error-light ";
          } else if (status === "unanswered") {
            baseClass +=
              "border-2 border-border-strong bg-surface-2 dark:border-border-strong dark:bg-surface-2 text-text-main dark:text-text-on-dark ";
          }
        }

        item.className = baseClass.trim();

        const label = document.createElement("span");
        label.className = "inline-flex h-5 w-5 items-center justify-center text-[11px]";
        label.textContent = String(idx + 1);
        item.appendChild(label);

        if (isAnswered) {
          const mark = document.createElement("span");
          mark.className = "text-[10px] text-success dark:text-success";
          mark.textContent = "✔";
          item.appendChild(mark);
        }

        if (isFlagged) {
          const flag = document.createElement("span");
          flag.className =
            "ml-1 text-[11px] text-warning dark:text-warning-light";
          flag.textContent = "⚑";
          item.appendChild(flag);
        }

        item.addEventListener("click", () => {
          state.currentIndex = idx;
          renderQuestionSidebarC1();
          renderQuestionViewC2C3C4();
        });

        list.appendChild(item);
      });
    }

    function renderQuestionHeaderC2() {
      const header = document.createElement("div");
      header.className =
        "flex items-center justify-between gap-2 border-b border-border-strong pb-1 dark:border-border-strong";

      const headerInfo = document.createElement("div");
      headerInfo.className = "flex flex-col";

      const title = document.createElement("div");
      title.className =
        "text-sm font-semibold text-text-main dark:text-text-on-dark";
      const meta = document.createElement("div");
      meta.className = "text-[11px] font-medium text-text-muted dark:text-text-muted";

      let currentQuestionId = null;
      let currentMeta = null;
      if (state.questions.length > 0) {
        const total = state.questions.length;
        const baseMeta = `Question ${state.currentIndex + 1} of ${total}`;
        title.textContent = baseMeta;
        if (state.difficulty != null) {
          meta.textContent = `Difficulty: ${state.difficulty}`;
        } else {
          meta.textContent = "";
        }
        currentMeta =
          state.questions[state.currentIndex] || state.questions[0];
        currentQuestionId = currentMeta.id;
      } else {
        title.textContent = "Question";
        meta.textContent = "No questions data in task";
      }

      headerInfo.appendChild(title);
      headerInfo.appendChild(meta);
      header.appendChild(headerInfo);

      // Кнопка-флаг для пометки вопроса
      const flagButton = document.createElement("button");
      flagButton.type = "button";
      flagButton.className =
        "inline-flex items-center gap-1 rounded-full border border-warning-light px-2 py-0.5 text-[11px] font-medium text-warning-text hover:bg-warning-lighter dark:border-warning dark:text-warning dark:hover:bg-warning-light disabled:opacity-60";
      const flagSpan = document.createElement("span");
      flagSpan.textContent = "⚑";
      const flagLabel = document.createElement("span");
      flagLabel.textContent = "Flag";
      flagButton.appendChild(flagSpan);
      flagButton.appendChild(flagLabel);

      if (!currentQuestionId) {
        flagButton.disabled = true;
      } else {
        const flagged = !!state.flags[currentQuestionId];
        if (flagged) {
          flagButton.className +=
            " bg-warning-lighter dark:bg-warning-light border-warning text-warning-dark dark:text-warning-light";
        }
        flagButton.addEventListener("click", () => {
          state.flags[currentQuestionId] = !flagged;
          renderQuestionSidebarC1();
          renderQuestionViewC2C3C4();
        });
      }

      header.appendChild(flagButton);

      return { header, currentMeta };
    }

    function renderQuestionViewC2C3C4() {
      const questionModule =
        (typeof TestUIQuestion !== "undefined" && TestUIQuestion) || null;

      if (questionModule && typeof questionModule.createQuestionRenderer === "function") {
        const renderer = questionModule.createQuestionRenderer(state, main);
        renderer.renderQuestionView();
        return;
      }

      // Fallback на инлайн-реализацию, если модуль вопроса не подключен
      main.innerHTML = "";

      const { header, currentMeta } = renderQuestionHeaderC2();
      const body = renderQuestionBodyC3(currentMeta);

      main.appendChild(header);
      main.appendChild(body);
    }

    // Делаем внутренние функции перерисовки доступными через state,
    // чтобы модуль TestUIQuestion мог обновлять сайдбар и текущий вопрос
    // после изменения ответов или навигации стрелками.
    state._rerenderSidebar = renderQuestionSidebarC1;
    state._rerenderQuestion = renderQuestionViewC2C3C4;
    state._notifyAnswerStateChanged = emitAnswerStateChanged;

    renderQuestionSidebarC1();
    renderQuestionViewC2C3C4();
    emitAnswerStateChanged();

    // Legend и дополнительная панель создаём только во fallback-режиме без кастомного layout.
    if (!usingCustomLayout) {
      const legend = document.createElement("div");
      legend.className =
        "mt-4 border-t border-border-strong dark:border-border-strong pt-3 space-y-2 text-[11px] text-text-muted dark:text-text-muted";

      function legendItem(boxClass, text) {
        const row = document.createElement("div");
        row.className = "flex items-center gap-2";
        const box = document.createElement("div");
        box.className = `${boxClass} task-chip`;
        const label = document.createElement("span");
        label.textContent = text;
        row.appendChild(box);
        row.appendChild(label);
        return row;
      }

      legend.appendChild(
        legendItem(
          "size-3 rounded-md bg-success",
          "Верный ответ"
        )
      );
      legend.appendChild(
        legendItem(
          "size-3 rounded-md bg-error",
          "Неверный ответ"
        )
      );
      legend.appendChild(
        legendItem(
          "size-3 rounded-md bg-primary", "Отвечен"
        )
      );
      legend.appendChild(
        legendItem(
          "size-3 rounded-md bg-surface-2 dark:bg-surface-2",
          "Посещен"
        )
      );
      legend.appendChild(
        legendItem(
          "size-3 rounded-md bg-bg-disabled dark:bg-bg-disabled",
          "Не посещен"
        )
      );

      const flagRow = document.createElement("div");
      flagRow.className = "flex items-center gap-2";
      const flagIcon = document.createElement("span");
      flagIcon.className =
        "material-symbols-outlined text-warning dark:text-warning text-base";
      flagIcon.textContent = "flag";
      const flagLabel = document.createElement("span");
      flagLabel.textContent = "Отмечен";
      flagRow.appendChild(flagIcon);
      flagRow.appendChild(flagLabel);
      legend.appendChild(flagRow);

      root.appendChild(main);
      sidebar.appendChild(legend);
      root.appendChild(sidebar);
    }

    containerElement.appendChild(root);

    return {
      get questions() {
        return state.questions;
      },
      get selections() {
        return state.selections;
      },
      getUserAnswerPayload() {
        const questionsList = Array.isArray(state.rawQuestions)
          ? state.rawQuestions
          : [];

        const answers = {};
        const textAnswers = {};

        state.questions.forEach((q) => {
          const qId = q.id;
          const val = state.answers[qId];
          if (val == null) {
            return;
          }
          if (state.isOpenMode && typeof val === "string") {
            textAnswers[qId] = val;
          } else {
            answers[qId] = val;
          }
        });

        return {
          type: "test",
          questions: questionsList,
          answers,
          text_answers: textAnswers,
        };
      },
      getAnswerProgress() {
        return buildAnswerProgressFromState(state);
      },
      applyCheckFeedback(result) {
        state.mode = "review";

        let perQuestion = null;
        if (result && result.details && result.details.per_question_ui) {
          perQuestion = result.details.per_question_ui;
        } else if (result && result.details && result.details.per_question) {
          perQuestion = result.details.per_question;
        } else if (result && result.per_question_ui) {
          perQuestion = result.per_question_ui;
        } else if (result && result.per_question) {
          perQuestion = result.per_question;
        }

        if (perQuestion && typeof perQuestion === "object") {
          state.questionResults = perQuestion;
        } else if (state && state.isOpenMode && Array.isArray(state.questions)) {
          // L2 open-text fallback: если бекенд не вернул per_question, но мы в open-режиме,
          // синтезируем простую карту статусов по всем вопросам.
          const synthesized = {};
          const globalSuccess = typeof result?.success === "boolean" ? result.success : null;

          state.questions.forEach((q) => {
            const qId = q && q.id != null ? q.id : null;
            if (!qId) return;

            const hasUserText =
              state.answers && typeof state.answers[qId] === "string" && state.answers[qId].trim() !== "";

            let status = "unanswered";
            if (hasUserText && globalSuccess === true) {
              status = "correct";
            } else if (hasUserText && globalSuccess === false) {
              status = "incorrect";
            }

            synthesized[qId] = {
              status,
            };
          });

          state.questionResults = synthesized;
        }

        renderQuestionSidebarC1();
        renderQuestionViewC2C3C4();
        emitAnswerStateChanged();
      },
    };
  }

  return {
    render(containerElement, task) {
      currentInstance = createRoot(containerElement, task);
    },
    getUserAnswerPayload() {
      if (
        currentInstance &&
        typeof currentInstance.getUserAnswerPayload === "function"
      ) {
        return currentInstance.getUserAnswerPayload();
      }
      return {};
    },
    getAnswerProgress() {
      if (
        currentInstance &&
        typeof currentInstance.getAnswerProgress === "function"
      ) {
        return currentInstance.getAnswerProgress();
      }
      return null;
    },
    applyCheckFeedback(result) {
      if (
        currentInstance &&
        typeof currentInstance.applyCheckFeedback === "function"
      ) {
        currentInstance.applyCheckFeedback(result);
      }
    },

    // Phase 2: Cleanup method to prevent memory leaks
    cleanup() {
      // Reset current instance
      currentInstance = null;
      // Note: TestUI uses inline event handlers via addEventListener in createRoot,
      // but they are attached to elements that will be removed from DOM,
      // so they will be garbage collected automatically.
      // No explicit listener removal needed.
    }
  };
})();
