// Extracted TestUI module from S1/index.html
// NOTE: This file is generated by refactoring and should stay in sync with S1 logic.

const TestUI = (function () {
  let currentInstance = null;

  function isImageOnlyAnswer(answer) {
    if (!answer || typeof answer !== "object") return false;
    const image = answer.image;
    return !!(
      answer.image_asset_id ||
      answer.image_asset_url ||
      answer.image_path ||
      answer.image_url ||
      (image &&
        typeof image === "object" &&
        (image.asset_id || image.asset_url || image.url || image.path))
    );
  }

  function areAllQuestionsImageOnly(rawQuestions) {
    if (!Array.isArray(rawQuestions) || !rawQuestions.length) return false;
    return rawQuestions.every((question) => {
      if (!question || typeof question !== "object") return false;
      const answers = Array.isArray(question.answers)
        ? question.answers
        : question.content && Array.isArray(question.content.answers)
          ? question.content.answers
          : [];
      return answers.length > 0 && answers.every(isImageOnlyAnswer);
    });
  }

  function buildAnswerProgressFromState(state) {
    const questions = Array.isArray(state && state.questions) ? state.questions : [];
    const totalQuestions = questions.length;
    const answers = state && state.answers && typeof state.answers === "object"
      ? state.answers
      : {};
    const answeredIds = new Set();

    Object.keys(answers).forEach((qid) => {
      const value = answers[qid];
      if (value == null) return;
      if (Array.isArray(value)) {
        if (value.length > 0) answeredIds.add(String(qid));
        return;
      }
      if (typeof value === "string") {
        if (value.trim().length > 0) answeredIds.add(String(qid));
        return;
      }
      answeredIds.add(String(qid));
    });

    const questionIds = questions.map((question, index) =>
      question && question.id != null ? String(question.id) : String(index)
    );
    const answeredQuestionIds = questionIds.filter((qid) => answeredIds.has(qid));
    const unansweredQuestionIds = questionIds.filter((qid) => !answeredIds.has(qid));
    const answeredCount = answeredQuestionIds.length;
    const unansweredCount = unansweredQuestionIds.length;

    return {
      totalQuestions,
      answeredCount,
      unansweredCount,
      answeredQuestionIds,
      unansweredQuestionIds,
      allAnswered: totalQuestions > 0 && unansweredCount === 0,
    };
  }

  function createRoot(containerElement, task) {
    if (!containerElement) {
      return null;
    }

    const core = (typeof TestUICore !== "undefined" && TestUICore) || null;
    const state = core && typeof core.createInitialState === "function"
      ? core.createInitialState(task)
      : (function fallbackCreateState() {
        // Fallback на случай, если TestUICore не подключен (например, старые окружения)
        const td = task && task.task_data;
        let raw = [];
        if (td && td.content && Array.isArray(td.content.questions)) {
          raw = td.content.questions;
        } else if (td && Array.isArray(td.questions)) {
          raw = td.questions;
        }

        const mapped = raw.map((q, idx) => ({
          id: q.id != null ? String(q.id) : `q_${idx + 1}`,
          index: idx,
          text: q.text || q.title || "Вопрос",
        }));

        const testType =
          (td && td.content && td.content.test_type) || (td && td.test_type) || "single_choice";

        const content = td && td.content;
        const difficultyFromTask =
          (task && (task.difficulty || (task.task_data && task.task_data.difficulty))) ||
          null;
        const isLevel2OrHigher =
          typeof difficultyFromTask === "number" && difficultyFromTask >= 2;

        const requiresTextInput = !!(content && content.requires_text_input);
        const showOptions =
          content && Object.prototype.hasOwnProperty.call(content, "show_options")
            ? !!content.show_options
            : true;
        const imageOnlyQuestions = areAllQuestionsImageOnly(raw);
        // L2 open-mode: либо явно требует текстового ввода, либо скрывает варианты,
        // либо уровень сложности 2+ (для второй итерации показываем поле ввода).
        const isOpenMode =
          requiresTextInput ||
          !showOptions ||
          (!imageOnlyQuestions && isLevel2OrHigher);

        const difficulty = difficultyFromTask;

        const questionResults = {};

        return {
          questions: mapped,
          rawQuestions: raw,
          testType,
          currentIndex: 0,
          selections: {},
          answers: {},
          isOpenMode,
          flags: {},
          // Индексы посещённых вопросов (для sidebar: Visited/Not visited)
          visitedIndices: { 0: true },
          mode: "answering",
          difficulty: difficultyFromTask,
          questionResults: {},
          pendingUnansweredQuestionIds: [],
        };
      })();

    // Нормализуем режимы в зависимости от сложности, независимо от источника state
    const difficultyFromTask =
      (task && (task.difficulty || (task.task_data && task.task_data.difficulty))) ||
      null;

    if (typeof difficultyFromTask === "number") {
      if (state && typeof state === "object") {
        if (state.difficulty == null) {
          state.difficulty = difficultyFromTask;
        }
        if (difficultyFromTask >= 2 && !areAllQuestionsImageOnly(state.rawQuestions)) {
          state.isOpenMode = true;
        }
      }
    }

    let root;
    let sidebar;
    let list;
    let main;

    const layout = (typeof TestUILayout !== "undefined" && TestUILayout) || null;
    const usingCustomLayout = !!(layout && typeof layout.createLayout === "function");

    // Гарантируем наличие visitedIndices в состоянии
    if (!state.visitedIndices) {
      state.visitedIndices = { [state.currentIndex]: true };
    }
    if (!Array.isArray(state.pendingUnansweredQuestionIds)) {
      state.pendingUnansweredQuestionIds = [];
    }

    function emitAnswerStateChanged() {
      const progress = buildAnswerProgressFromState(state);
      try {
        if (typeof window !== "undefined" && typeof window.dispatchEvent === "function" && typeof CustomEvent === "function") {
          window.dispatchEvent(new CustomEvent("test:answer-state-changed", { detail: progress }));
        }
      } catch (e) {
        // ignore
      }
      return progress;
    }

    if (usingCustomLayout) {
      const created = layout.createLayout();
      root = created.root;
      sidebar = created.sidebar;
      list = created.list;
      main = created.main;
    } else {
      // Fallback layout без кастомного модуля: повторяем структуру L1-M1/L1-SPEC
      root = document.createElement("div");
      root.className =
        "grid items-start gap-6 lg:grid-cols-3 xl:grid-cols-4";

      main = document.createElement("div");
      main.className =
        "lg:col-span-2 xl:col-span-3 flex min-h-[120px] flex-col gap-2";

      sidebar = document.createElement("aside");
      sidebar.className =
        "ml-auto flex w-full max-w-sm flex-col lg:col-span-1 xl:col-span-1";

      const sidebarCard = document.createElement("div");
      sidebarCard.className =
        "sticky top-0 h-fit overflow-hidden rounded-2xl border border-border-strong bg-surface-2 p-5 shadow-sm dark:border-border-strong dark:bg-surface-2";

      const sidebarHeader = document.createElement("div");
      sidebarHeader.className = "mb-4 flex items-center justify-between gap-3";
      const sidebarTitle = document.createElement("h3");
      sidebarTitle.className =
        "text-lg font-bold tracking-tight text-text-main dark:text-text-on-dark";
      sidebarTitle.textContent = "Вопросы";
      sidebarHeader.appendChild(sidebarTitle);

      const sidebarMeta = document.createElement("span");
      sidebarMeta.className =
        "inline-flex items-center rounded-full border border-border-strong bg-surface-1 px-2.5 py-1 text-[11px] font-semibold tracking-[0.04em] text-text-secondary dark:border-border-strong dark:bg-surface-1 dark:text-text-secondary";
      sidebarMeta.textContent = `${state.questions.length || 0}`;
      sidebarHeader.appendChild(sidebarMeta);
      sidebarCard.appendChild(sidebarHeader);

      list = document.createElement("ol");
      list.className = "grid grid-cols-5 gap-2.5";
      sidebarCard.appendChild(list);
      sidebar.appendChild(sidebarCard);

      root.appendChild(main);
      root.appendChild(sidebar);
    }

    function renderQuestionSidebarC1() {
      const sidebarModule =
        (typeof TestUISidebar !== "undefined" && TestUISidebar) || null;

      if (sidebarModule && typeof sidebarModule.renderSidebar === "function") {
        sidebarModule.renderSidebar({
          state,
          listElement: list,
          onSelectQuestion: (idx) => {
            state.currentIndex = idx;
            state.visitedIndices = state.visitedIndices || {};
            state.visitedIndices[idx] = true;
            renderQuestionSidebarC1();
            renderQuestionViewC2C3C4();
          },
        });
        return;
      }

      // Fallback на инлайн-реализацию, если модуль сайдбара не подключен
      list.innerHTML = "";
      if (state.questions.length === 0) {
        const empty = document.createElement("li");
        empty.className =
          "col-span-4 rounded-md border-2 border-dashed border-border-strong bg-surface-2 px-2 py-2 text-center text-xs text-text-muted dark:border-border-strong dark:bg-surface-2 dark:text-text-muted";
        empty.textContent = "Нет вопросов";
        list.appendChild(empty);
        return;
      }

      state.questions.forEach((q, idx) => {
        const item = document.createElement("li");
        const isCurrent = idx === state.currentIndex;
        const isAnswered = !!state.selections[q.id];
        const pendingUnansweredIds = new Set(
          Array.isArray(state.pendingUnansweredQuestionIds)
            ? state.pendingUnansweredQuestionIds.map((questionId) => String(questionId))
            : []
        );
        const isPendingUnanswered =
          !isAnswered && pendingUnansweredIds.has(String(q.id));
        const isFlagged = !!state.flags[q.id];
        const qr = state.questionResults && state.questionResults[q.id];
        const status = qr && qr.status;

        let baseClass =
          "relative flex items-center justify-center size-9 md:size-10 rounded-lg border-2 border-border-strong bg-surface-2 text-xs font-semibold text-text-main cursor-pointer select-none transition-colors dark:border-border-strong dark:bg-surface-2 dark:text-text-on-dark ";

        if (isPendingUnanswered && !status) {
          baseClass =
            "relative flex items-center justify-center size-9 md:size-10 rounded-lg border-2 border-warning-light bg-warning-lighter text-warning-darker text-xs font-semibold cursor-pointer select-none shadow-sm transition-colors";
        } else if (isCurrent && !status) {
          baseClass =
            "relative flex items-center justify-center size-9 md:size-10 rounded-lg bg-primary text-primary-fg text-xs font-semibold cursor-pointer select-none shadow-sm transition-colors";
        } else if (!status && isAnswered) {
          baseClass =
            "relative flex items-center justify-center size-9 md:size-10 rounded-lg bg-primary text-primary-fg text-xs font-semibold cursor-pointer select-none transition-colors";
        } else if (!status && !isAnswered) {
          baseClass +=
            "bg-surface-2 hover:bg-surface-2 dark:bg-surface-2 dark:hover:bg-bg-hover ";
        }

        if (state.mode === "review" && status) {
          if (status === "correct") {
            baseClass +=
              "border-2 border-success bg-success-light dark:bg-success-light text-success-text dark:text-success-light ";
          } else if (status === "incorrect") {
            baseClass +=
              "border-2 border-error bg-error-light dark:bg-error-light text-error-dark dark:text-error-light ";
          } else if (status === "unanswered") {
            baseClass +=
              "border-2 border-border-strong bg-surface-2 dark:border-border-strong dark:bg-surface-2 text-text-main dark:text-text-on-dark ";
          }
        }

        item.className = baseClass.trim();

        const label = document.createElement("span");
        label.className = "inline-flex h-5 w-5 items-center justify-center text-[11px]";
        label.textContent = String(idx + 1);
        item.appendChild(label);

        if (isAnswered) {
          const mark = document.createElement("span");
          mark.className = "text-[10px] text-success dark:text-success";
          mark.textContent = "✔";
          item.appendChild(mark);
        }

        if (isFlagged) {
          const flag = document.createElement("span");
          flag.className =
            "ml-1 text-[11px] text-warning dark:text-warning-light";
          flag.textContent = "⚑";
          item.appendChild(flag);
        }

        item.addEventListener("click", () => {
          state.currentIndex = idx;
          renderQuestionSidebarC1();
          renderQuestionViewC2C3C4();
        });

        list.appendChild(item);
      });
    }

    function renderQuestionHeaderC2() {
      const header = document.createElement("div");
      header.className =
        "flex items-center justify-between gap-3 border-b border-border-strong pb-2 dark:border-border-strong";

      const headerInfo = document.createElement("div");
      headerInfo.className = "flex flex-col";

      const title = document.createElement("div");
      title.className =
        "text-sm font-semibold tracking-tight text-text-main dark:text-text-on-dark";
      const meta = document.createElement("div");
      meta.className = "text-[11px] font-medium tracking-[0.02em] text-text-muted dark:text-text-muted";

      let currentQuestionId = null;
      let currentMeta = null;
      if (state.questions.length > 0) {
        const total = state.questions.length;
        const baseMeta = `Вопрос ${state.currentIndex + 1} из ${total}`;
        title.textContent = baseMeta;
        if (state.difficulty != null) {
          meta.textContent = `Сложность: ${state.difficulty}`;
        } else {
          meta.textContent = "";
        }
        currentMeta =
          state.questions[state.currentIndex] || state.questions[0];
        currentQuestionId = currentMeta.id;
      } else {
        title.textContent = "Вопрос";
        meta.textContent = "В задании нет вопросов";
      }

      headerInfo.appendChild(title);
      headerInfo.appendChild(meta);
      header.appendChild(headerInfo);

      // Кнопка-флаг для пометки вопроса
      const flagButton = document.createElement("button");
      flagButton.type = "button";
      flagButton.className =
        "inline-flex items-center gap-1 rounded-full border border-warning-light px-2.5 py-1 text-[11px] font-medium text-warning-text shadow-sm hover:bg-warning-lighter dark:border-warning dark:text-warning dark:hover:bg-warning-light disabled:opacity-60";
      const flagSpan = document.createElement("span");
      flagSpan.textContent = "⚑";
      const flagLabel = document.createElement("span");
      flagLabel.textContent = "Пометить";
      flagButton.appendChild(flagSpan);
      flagButton.appendChild(flagLabel);

      if (!currentQuestionId) {
        flagButton.disabled = true;
      } else {
        const flagged = !!state.flags[currentQuestionId];
        if (flagged) {
          flagButton.className +=
            " bg-warning-lighter dark:bg-warning-light border-warning text-warning-dark dark:text-warning-light";
        }
        flagButton.addEventListener("click", () => {
          state.flags[currentQuestionId] = !flagged;
          renderQuestionSidebarC1();
          renderQuestionViewC2C3C4();
        });
      }

      header.appendChild(flagButton);

      return { header, currentMeta };
    }

    function renderQuestionViewC2C3C4() {
      const questionModule =
        (typeof TestUIQuestion !== "undefined" && TestUIQuestion) || null;

      if (questionModule && typeof questionModule.createQuestionRenderer === "function") {
        const renderer = questionModule.createQuestionRenderer(state, main);
        renderer.renderQuestionView();
        return;
      }

      // Fallback на инлайн-реализацию, если модуль вопроса не подключен
      main.innerHTML = "";

      const { header, currentMeta } = renderQuestionHeaderC2();
      const body = renderQuestionBodyC3(currentMeta);

      main.appendChild(header);
      main.appendChild(body);
    }

    // Делаем внутренние функции перерисовки доступными через state,
    // чтобы модуль TestUIQuestion мог обновлять сайдбар и текущий вопрос
    // после изменения ответов или навигации стрелками.
    state._rerenderSidebar = renderQuestionSidebarC1;
    state._syncSidebarQuestion = function syncSidebarQuestion(questionIndex) {
      const sidebarModule =
        (typeof TestUISidebar !== "undefined" && TestUISidebar) || null;
      if (
        sidebarModule &&
        typeof sidebarModule.syncSidebarQuestion === "function"
      ) {
        sidebarModule.syncSidebarQuestion({
          state,
          listElement: list,
          questionIndex,
        });
        return;
      }
      renderQuestionSidebarC1();
    };
    state._rerenderQuestion = renderQuestionViewC2C3C4;
    state._notifyAnswerStateChanged = emitAnswerStateChanged;

    renderQuestionSidebarC1();
    renderQuestionViewC2C3C4();
    emitAnswerStateChanged();

    // Legend и дополнительная панель создаём только во fallback-режиме без кастомного layout.
    if (!usingCustomLayout && state.questions.length > 1) {
      const legend = document.createElement("div");
      legend.className =
        "mt-4 rounded-2xl border border-border-strong bg-surface-2 px-3 py-3 text-[11px] text-text-main shadow-sm dark:border-border-strong dark:bg-surface-2 dark:text-text-on-dark";

      const legendTitle = document.createElement("div");
      legendTitle.className =
        "mb-3 text-[11px] font-semibold uppercase tracking-[0.08em] text-text-secondary dark:text-text-secondary";
      legendTitle.textContent = "Обозначения";
      legend.appendChild(legendTitle);

      const legendGrid = document.createElement("div");
      legendGrid.className = "grid grid-cols-2 gap-2";

      function legendItem(boxClass, text) {
        const row = document.createElement("div");
        row.className =
          "flex items-center gap-2 rounded-xl border border-border-strong bg-surface-1 px-2.5 py-2 text-[11px] font-medium text-text-secondary dark:border-border-strong dark:bg-surface-1 dark:text-text-secondary";
        const box = document.createElement("div");
        box.className = `${boxClass} task-chip`;
        const label = document.createElement("span");
        label.textContent = text;
        row.appendChild(box);
        row.appendChild(label);
        return row;
      }

      legendGrid.appendChild(
        legendItem(
          "size-3 rounded-md bg-success",
          "Верный ответ"
        )
      );
      legendGrid.appendChild(
        legendItem(
          "size-3 rounded-md bg-error",
          "Неверный ответ"
        )
      );
      legendGrid.appendChild(
        legendItem(
          "size-3 rounded-md bg-primary", "Отвечен"
        )
      );
      legendGrid.appendChild(
        legendItem(
          "size-3 rounded-md border border-border-strong bg-surface-2 dark:border-border-strong dark:bg-surface-2",
          "Посещен"
        )
      );
      legendGrid.appendChild(
        legendItem(
          "size-3 rounded-md border border-dashed border-border-strong bg-transparent dark:border-border-strong dark:bg-transparent",
          "Не посещен"
        )
      );

      const flagRow = document.createElement("div");
      flagRow.className =
        "flex items-center gap-2 rounded-xl border border-border-strong bg-surface-1 px-2.5 py-2 text-[11px] font-medium text-text-secondary dark:border-border-strong dark:bg-surface-1 dark:text-text-secondary";
      const flagIcon = document.createElement("span");
      flagIcon.className =
        "material-symbols-outlined text-warning dark:text-warning text-base";
      flagIcon.textContent = "flag";
      const flagLabel = document.createElement("span");
      flagLabel.textContent = "Отмечен";
      flagRow.appendChild(flagIcon);
      flagRow.appendChild(flagLabel);
      legendGrid.appendChild(flagRow);

      legend.appendChild(legendGrid);

      root.appendChild(main);
      sidebar.appendChild(legend);
      root.appendChild(sidebar);
    }

    containerElement.appendChild(root);

    function buildSelectionsFromAnswers(answersMap) {
      const nextSelections = {};
      if (!answersMap || typeof answersMap !== "object") {
        return nextSelections;
      }

      Object.keys(answersMap).forEach((questionId) => {
        const value = answersMap[questionId];
        if (Array.isArray(value)) {
          if (value.length > 0) {
            nextSelections[questionId] = true;
          }
          return;
        }
        if (typeof value === "string") {
          if (value.trim().length > 0) {
            nextSelections[questionId] = true;
          }
          return;
        }
        if (value != null) {
          nextSelections[questionId] = true;
        }
      });

      return nextSelections;
    }

    function getBackendQuestionAnswerKey(question, index) {
      const raw =
        (Array.isArray(state.rawQuestions) && state.rawQuestions[index]) || null;
      if (raw && raw.id != null) return String(raw.id);
      if (question && question.index != null) return String(question.index);
      return String(index);
    }

    function hasMeaningfulAnswerValue(value) {
      if (Array.isArray(value)) return value.length > 0;
      if (typeof value === "string") return value.trim().length > 0;
      return value != null;
    }

    function getQuestionResultLookupKeys(question, index) {
      const keys = [];
      const push = (value) => {
        if (value == null) return;
        const normalized = String(value);
        if (!normalized || keys.includes(normalized)) return;
        keys.push(normalized);
      };

      push(question && question.id);
      const raw =
        (Array.isArray(state.rawQuestions) && state.rawQuestions[index]) || null;
      push(raw && raw.id);
      push(question && question.index);
      push(index);
      push(`q_${index + 1}`);

      return keys;
    }

    function inferQuestionStatusFromResult(resultItem, questionId) {
      if (!resultItem || typeof resultItem !== "object") return null;

      const rawStatus = String(resultItem.status || "").trim().toLowerCase();
      if (
        rawStatus === "correct" ||
        rawStatus === "incorrect" ||
        rawStatus === "unanswered"
      ) {
        return rawStatus;
      }

      const details =
        resultItem.details && typeof resultItem.details === "object"
          ? resultItem.details
          : {};
      const reason = String(resultItem.reason || details.reason || "")
        .trim()
        .toLowerCase();
      if (reason === "not_answered" || reason === "no_answers") {
        return "unanswered";
      }

      if (resultItem.correct === true || resultItem.is_correct === true) {
        return "correct";
      }

      if (resultItem.correct === false || resultItem.is_correct === false) {
        const answerValue =
          resultItem.user_answer !== undefined
            ? resultItem.user_answer
            : details.user_answer !== undefined
              ? details.user_answer
              : state.answers && questionId != null
                ? state.answers[questionId]
                : undefined;
        return hasMeaningfulAnswerValue(answerValue) ? "incorrect" : "unanswered";
      }

      return null;
    }

    function normalizePerQuestionFeedback(perQuestion) {
      if (!perQuestion || typeof perQuestion !== "object" || Array.isArray(perQuestion)) {
        return null;
      }

      const normalized = {};
      let matchedCount = 0;

      state.questions.forEach((question, index) => {
        const questionId = question && question.id != null ? String(question.id) : null;
        if (!questionId) return;

        const keys = getQuestionResultLookupKeys(question, index);
        let matchedItem;
        let hasMatch = false;

        for (const key of keys) {
          if (Object.prototype.hasOwnProperty.call(perQuestion, key)) {
            matchedItem = perQuestion[key];
            hasMatch = true;
            break;
          }
        }

        if (!hasMatch) return;
        normalized[questionId] = matchedItem;
        matchedCount += 1;
      });

      if (matchedCount === 0) {
        return perQuestion;
      }

      return normalized;
    }

    function normalizeQuestionResultsList(questionResults) {
      if (!Array.isArray(questionResults) || questionResults.length === 0) {
        return null;
      }

      const normalized = {};
      let matchedCount = 0;

      state.questions.forEach((question, index) => {
        const questionId = question && question.id != null ? String(question.id) : null;
        if (!questionId) return;

        const keys = getQuestionResultLookupKeys(question, index);
        const matchedItem = questionResults.find((resultItem, resultIndex) => {
          if (!resultItem || typeof resultItem !== "object") return false;
          if (resultItem.question_id != null) {
            return keys.includes(String(resultItem.question_id));
          }
          if (resultItem.id != null) {
            return keys.includes(String(resultItem.id));
          }
          if (Number.isInteger(resultItem.index)) {
            return resultItem.index === index;
          }
          return resultIndex === index;
        });

        if (!matchedItem) return;

        const status = inferQuestionStatusFromResult(matchedItem, questionId);
        normalized[questionId] = status
          ? { ...matchedItem, status }
          : { ...matchedItem };
        matchedCount += 1;
      });

      return matchedCount > 0 ? normalized : null;
    }

    function synthesizeQuestionResultsFromGlobalResult(result) {
      if (!Array.isArray(state.questions) || state.questions.length === 0) {
        return null;
      }

      const globalSuccess = typeof result?.success === "boolean" ? result.success : null;
      const synthesized = {};

      state.questions.forEach((question) => {
        const questionId = question && question.id != null ? String(question.id) : null;
        if (!questionId) return;

        const answerValue = state.answers && state.answers[questionId];
        const hasAnswer = hasMeaningfulAnswerValue(answerValue);
        let status = "unanswered";
        if (hasAnswer && globalSuccess === true) {
          status = "correct";
        } else if (hasAnswer && globalSuccess === false) {
          status = "incorrect";
        }
        synthesized[questionId] = { status };
      });

      return synthesized;
    }

    return {
      get questions() {
        return state.questions;
      },
      get selections() {
        return state.selections;
      },
      getUserAnswerPayload() {
        const questionsList = Array.isArray(state.rawQuestions)
          ? state.rawQuestions
          : [];

        const answers = {};
        const textAnswers = {};

        state.questions.forEach((q, index) => {
          const qId = q.id;
          const val = state.answers[qId];
          if (val == null) {
            return;
          }
          const backendKey = getBackendQuestionAnswerKey(q, index);
          if (state.isOpenMode && typeof val === "string") {
            textAnswers[qId] = val;
            if (backendKey !== qId) {
              textAnswers[backendKey] = val;
            }
          } else {
            answers[qId] = val;
            if (backendKey !== qId) {
              answers[backendKey] = Array.isArray(val) ? val.slice() : val;
            }
          }
        });

        return {
          type: "test",
          questions: questionsList,
          answers,
          text_answers: textAnswers,
        };
      },
      restoreInput(draft) {
        if (!draft || typeof draft !== "object") {
          return;
        }

        const nextAnswers = {};
        const answerGroups = [];
        if (draft.answers && typeof draft.answers === "object") {
          answerGroups.push(draft.answers);
        }
        if (draft.text_answers && typeof draft.text_answers === "object") {
          answerGroups.push(draft.text_answers);
        }

        answerGroups.forEach((group) => {
          Object.keys(group).forEach((questionId) => {
            const value = group[questionId];
            if (Array.isArray(value)) {
              nextAnswers[questionId] = value.slice();
            } else if (
              typeof value === "string" ||
              typeof value === "number" ||
              typeof value === "boolean"
            ) {
              nextAnswers[questionId] = value;
            }
          });
        });

        state.answers = nextAnswers;
        state.selections = buildSelectionsFromAnswers(nextAnswers);
        state.visitedIndices = state.visitedIndices || {};
        state.visitedIndices[state.currentIndex] = true;

        renderQuestionSidebarC1();
        renderQuestionViewC2C3C4();
        emitAnswerStateChanged();
      },
      getViewState() {
        const visitedIndices = Object.keys(state.visitedIndices || {})
          .map((idx) => Number(idx))
          .filter((idx) => Number.isInteger(idx) && idx >= 0)
          .sort((a, b) => a - b);

        return {
          current_index: Number.isInteger(state.currentIndex) ? state.currentIndex : 0,
          visited_indices: visitedIndices,
          sidebar_scroll_top:
            list && typeof list.scrollTop === "number" ? list.scrollTop : 0,
        };
      },
      restoreViewState(viewState) {
        if (!viewState || typeof viewState !== "object") {
          return;
        }

        const totalQuestions = Array.isArray(state.questions) ? state.questions.length : 0;
        const requestedIndex = Number(viewState.current_index);
        const safeIndex =
          totalQuestions > 0 && Number.isInteger(requestedIndex)
            ? Math.max(0, Math.min(totalQuestions - 1, requestedIndex))
            : 0;
        state.currentIndex = safeIndex;

        const nextVisitedIndices = {};
        const rawVisited = viewState.visited_indices;
        if (Array.isArray(rawVisited)) {
          rawVisited.forEach((idx) => {
            const numericIndex = Number(idx);
            if (
              Number.isInteger(numericIndex) &&
              numericIndex >= 0 &&
              (totalQuestions === 0 || numericIndex < totalQuestions)
            ) {
              nextVisitedIndices[numericIndex] = true;
            }
          });
        } else if (rawVisited && typeof rawVisited === "object") {
          Object.keys(rawVisited).forEach((idx) => {
            const numericIndex = Number(idx);
            if (
              rawVisited[idx] &&
              Number.isInteger(numericIndex) &&
              numericIndex >= 0 &&
              (totalQuestions === 0 || numericIndex < totalQuestions)
            ) {
              nextVisitedIndices[numericIndex] = true;
            }
          });
        }
        nextVisitedIndices[state.currentIndex] = true;
        state.visitedIndices = nextVisitedIndices;

        renderQuestionSidebarC1();
        renderQuestionViewC2C3C4();

        const sidebarScrollTop = Number(viewState.sidebar_scroll_top);
        if (list && Number.isFinite(sidebarScrollTop)) {
          list.scrollTop = Math.max(0, sidebarScrollTop);
        }

        emitAnswerStateChanged();
      },
      getAnswerProgress() {
        return buildAnswerProgressFromState(state);
      },
      setPendingUnansweredQuestionIds(questionIds) {
        state.pendingUnansweredQuestionIds = Array.isArray(questionIds)
          ? questionIds.map((questionId) => String(questionId))
          : [];
        renderQuestionSidebarC1();
      },
      clearPendingUnansweredQuestionIds() {
        if (!Array.isArray(state.pendingUnansweredQuestionIds) || state.pendingUnansweredQuestionIds.length === 0) {
          return;
        }
        state.pendingUnansweredQuestionIds = [];
        renderQuestionSidebarC1();
      },
      applyCheckFeedback(result) {
        state.mode = "review";
        state.pendingUnansweredQuestionIds = [];

        let perQuestion = null;
        if (result && result.details && result.details.per_question_ui) {
          perQuestion = result.details.per_question_ui;
        } else if (result && result.details && result.details.per_question) {
          perQuestion = result.details.per_question;
        } else if (result && result.per_question_ui) {
          perQuestion = result.per_question_ui;
        } else if (result && result.per_question) {
          perQuestion = result.per_question;
        }

        if (perQuestion && typeof perQuestion === "object") {
          state.questionResults = normalizePerQuestionFeedback(perQuestion) || {};
        } else {
          const questionResults =
            result && result.details && Array.isArray(result.details.question_results)
              ? result.details.question_results
              : result && Array.isArray(result.question_results)
                ? result.question_results
                : null;
          state.questionResults =
            normalizeQuestionResultsList(questionResults) ||
            synthesizeQuestionResultsFromGlobalResult(result) ||
            {};
        }

        renderQuestionSidebarC1();
        renderQuestionViewC2C3C4();
        emitAnswerStateChanged();
      },
    };
  }

  return {
    render(containerElement, task) {
      currentInstance = createRoot(containerElement, task);
    },
    getUserAnswerPayload() {
      if (
        currentInstance &&
        typeof currentInstance.getUserAnswerPayload === "function"
      ) {
        return currentInstance.getUserAnswerPayload();
      }
      return {};
    },
    getAnswerProgress() {
      if (
        currentInstance &&
        typeof currentInstance.getAnswerProgress === "function"
      ) {
        return currentInstance.getAnswerProgress();
      }
      return null;
    },
    restoreInput(draft) {
      if (
        currentInstance &&
        typeof currentInstance.restoreInput === "function"
      ) {
        currentInstance.restoreInput(draft);
      }
    },
    getViewState() {
      if (
        currentInstance &&
        typeof currentInstance.getViewState === "function"
      ) {
        return currentInstance.getViewState();
      }
      return null;
    },
    restoreViewState(viewState) {
      if (
        currentInstance &&
        typeof currentInstance.restoreViewState === "function"
      ) {
        currentInstance.restoreViewState(viewState);
      }
    },
    setPendingUnansweredQuestionIds(questionIds) {
      if (
        currentInstance &&
        typeof currentInstance.setPendingUnansweredQuestionIds === "function"
      ) {
        currentInstance.setPendingUnansweredQuestionIds(questionIds);
      }
    },
    clearPendingUnansweredQuestionIds() {
      if (
        currentInstance &&
        typeof currentInstance.clearPendingUnansweredQuestionIds === "function"
      ) {
        currentInstance.clearPendingUnansweredQuestionIds();
      }
    },
    applyCheckFeedback(result) {
      if (
        currentInstance &&
        typeof currentInstance.applyCheckFeedback === "function"
      ) {
        currentInstance.applyCheckFeedback(result);
      }
    },

    // Phase 2: Cleanup method to prevent memory leaks
    cleanup() {
      // Reset current instance
      currentInstance = null;
      // Note: TestUI uses inline event handlers via addEventListener in createRoot,
      // but they are attached to elements that will be removed from DOM,
      // so they will be garbage collected automatically.
      // No explicit listener removal needed.
    }
  };
})();
